luncliff/vcpkg-registry

- azure-pipelines.yml
- azure/run-vcpkg-with-overlay.yml
- ports/vcpkg-host-python3-test/portfile.cmake
- ports/vcpkg-host-python3-test/requirements.txt
- ports/vcpkg-host-python3-test/vcpkg-port-config.cmake
- ports/vcpkg-host-python3-test/vcpkg.json
- ports/vcpkg-host-python3/LICENSE
- ports/vcpkg-host-python3/portfile.cmake
- ports/vcpkg-host-python3/vcpkg-port-config.cmake
- ports/vcpkg-host-python3/vcpkg.json
- ports/vcpkg-host-python3/vcpkg_pip_install.cmake
- ports/vcpkg-host-python3/vcpkg_pip_install_requirement.cmake
Need more detailed descriptions in `.cmake` and `.md`, but that will be done later...
> New port 'vcpkg-host-python3' and CI steps for Python3

- .clang-format
- azure-pipelines.yml
- ports/vulkan-android-test/CMakeLists.txt
- ports/vulkan-android-test/libmain.cpp
- ports/vulkan-android-test/portfile.cmake
- ports/vulkan-android-test/vcpkg.json
- triplets/arm-android.cmake
- triplets/arm64-android.cmake
- triplets/x64-android.cmake
Update triplet files for `x64-android`, `arm64-android`, `arm-android`
> Update Android triplets

- azure-pipelines.yml
- azure/jobs-windows.yml
> CI: Group port stage jobs to reduce build stress

- azure-pipelines.yml
- ports/libdispatch/vcpkg.json
* `libdispatch` https://github.com/apple/swift-corelibs-libdispatch/releases/tag/swift-5.5-RELEASE
* install `libdispatch` in `arm64-android`, `arm-android`, `x64-android`
* #8
> [libdispatch] support Android build

- ports/openssl3/portfile.cmake
- ports/openssl3/vcpkg.json
- versions/baseline.json
- versions/o-/openssl3.json
* `openssl3` : version 3.0.0 to 3.0.1
* [OpenSSL ChangeLog for 3.0.1](https://www.openssl.org/news/changelog.html#openssl-30)
> [openss3] version up to 3.0.1

- azure-pipelines.yml
- ports/metal-cpp/MetalCppConfig.cmake
- ports/metal-cpp/portfile.cmake
- ports/metal-cpp/usage
- ports/metal-cpp/vcpkg.json
- versions/baseline.json
- versions/m-/metal-cpp.json
* `metal-cpp` https://developer.apple.com/metal/cpp/
* install `metal-cpp` in `x64-osx`, `arm64-osx`, `arm64-ios`
> [metal-cpp] create a new port

- azure-pipelines.yml
- ports/directml/portfile.cmake
- ports/directml/vcpkg.json
- versions/baseline.json
- versions/d-/directml.json
* `directml` https://github.com/microsoft/DirectML
* install `directml` in `windows` triplets
* install `directml` in `x64-linux` triplet
* [Microsoft.AI.DirectML 1.6.0](https://www.nuget.org/packages/Microsoft.AI.DirectML/1.6.0)
> [directml] create a new port

- azure-pipelines.yml
- ports/farmhash/vcpkg.json
- versions/baseline.json
- versions/f-/farmhash.json
* `farmhash` 
* install `farmhash` in `arm64-android`, `arm-android`, `x64-android`, `arm64-osx`, `arm64-ios`
* #12
* #7
> [farmhash] remove ARM constraint

- azure-pipelines.yml
- ports/gemmlowp/portfile.cmake
- ports/gemmlowp/vcpkg.json
- versions/baseline.json
- versions/g-/gemmlowp.json
* Project: https://github.com/google/gemmlowp
* 2021/12
* `x64-osx`
* `x64-linux`
```json
{
{
"kind": "git",
"packages": [
"gemmlowp"
],
}
]
}
```
> [gemmlowp] create a new port

- azure-pipelines.yml
- ports/eigen3/fix-vectorized-reductions-half.patch
- ports/eigen3/portfile.cmake
- ports/eigen3/remove_configure_checks.patch
- ports/eigen3/vcpkg.json
- versions/baseline.json
- versions/e-/eigen3.json
* Eigen3 won't use Fortran in Android triplet
* Update VM image to [Ubuntu 22.04](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md)
> CI: Fix Android failure

- triplets/x86-android.cmake
- `android-x86`
- https://github.com/luncliff/vcpkg-registry/pull/51
> Add android-x86 triplet

- ports/tensorflow-lite/fix-cmake-android.patch
- ports/tensorflow-lite/portfile.cmake
- ports/tensorflow-lite/vcpkg.json
- triplets/x86-android.cmake
- versions/baseline.json
- versions/t-/tensorflow-lite.json
* `arm-android`
* #50 
* #49
* #53
> [tensorflow-lite] fix android link errors

- azure-pipelines.yml
- ports/directml/portfile.cmake
- ports/directml/vcpkg.json
- versions/baseline.json
- versions/d-/directml.json
* Project: https://github.com/microsoft/DirectML
* https://www.nuget.org/packages/Microsoft.AI.DirectML 1.8.2 
* `x64-linux`
```bash
vcpkg install directml
```
```ps1
vcpkg install directml
```
```json
{
{
"kind": "git",
"packages": [
"directml"
],
}
]
}
```
> [directml] update to 1.8.2

- azure-pipelines.yml
- ports/coreml-tools/fix-cmake.patch
- ports/coreml-tools/fix-sources.patch
- ports/coreml-tools/portfile.cmake
- ports/coreml-tools/vcpkg.json
- versions/baseline.json
- versions/c-/coreml-tools.json
* https://coremltools.readme.io/docs
* https://github.com/apple/coremltools/tree/6.1
* `x64-osx`
* `arm64-osx`
```json
{
{
"kind": "git",
"packages": [
"coreml-tools"
],
}
]
}
```
> [coreml-tools] create a new port

- azure-pipelines.yml
- ports/coreml-tools/fix-cmake.patch
- ports/coreml-tools/portfile.cmake
- ports/coreml-tools/vcpkg.json
- versions/baseline.json
- versions/c-/coreml-tools.json
* https://github.com/apple/coremltools
* `x64-osx`
* `arm64-osx`
* `arm64-ios`
* `x64-ios-simulator`
```json
{
{
"kind": "git",
"packages": [
"coreml-tools"
],
}
]
}
```
> [coreml-tools] support iOS build

- ports/coreml-tools/portfile.cmake
- ports/coreml-tools/vcpkg.json
- ports/tensorflow-lite/fix-cmake.patch
- ports/tensorflow-lite/fix-opencl-extension.patch
- ports/tensorflow-lite/fix-source.patch
- ports/tensorflow-lite/portfile.cmake
- ports/tensorflow-lite/vcpkg.json
- versions/baseline.json
- versions/c-/coreml-tools.json
- versions/t-/tensorflow-lite.json
* https://github.com/tensorflow/tensorflow/releases/tag/v2.10.1
* `x64-osx`
* `arm64-osx`
* `arm64-ios`
```json
{
{
"kind": "git",
"packages": [
],
}
]
}
```
> [tensorflow-lite] update to 2.10.1, use `coreml-tools`

- ports/tensorflow-lite/fix-cmake.patch
- ports/tensorflow-lite/portfile.cmake
- ports/tensorflow-lite/vcpkg.json
- versions/baseline.json
- versions/t-/tensorflow-lite.json
* https://github.com/tensorflow/tensorflow/releases/tag/v2.11.1
* `x64-uwp`
* `arm64-ios`
* `arm64-osx`
* `x64-osx`
```json
{
{
"kind": "git",
"packages": [
],
}
]
}
```
> [tensorflow-lite] update to 2.11.1

- ports/tensorflow-lite/fix-absl.patch
- ports/tensorflow-lite/fix-cmake.patch
- ports/tensorflow-lite/fix-source.patch
- ports/tensorflow-lite/org_tensorflow_compatibility_fixes.diff
- ports/tensorflow-lite/org_tensorflow_custom_ops.diff
- ports/tensorflow-lite/portfile.cmake
- ports/tensorflow-lite/vcpkg.json
* Afterwork of #96 
* Apply Google/MediaPipe patches from https://github.com/google/mediapipe/tree/master/third_party
* New feature `mediapipe` which enables MediaPipe delegates
```json
{
{
"kind": "git",
"packages": [
],
}
]
}
```
> [tensorflow-lite] correct GPU/EGL delegate support

- ports/fft2d/portfile.cmake
- ports/fft2d/vcpkg.json
- versions/baseline.json
- versions/f-/fft2d.json
Resolve #104
All supported triplets
> [fft2d] fix header installation

- ports/directml/portfile.cmake
- ports/directml/vcpkg.json
- versions/baseline.json
- versions/d-/directml.json
Resolve #37
* `directml` references https://www.nuget.org/packages/Microsoft.AI.DirectML/1.12.1
> [directml] Update to 1.12.1

- .github/workflows/build-macos.yml
- .github/workflows/build-ubuntu.yml
- azure-pipelines.yml
- ports/openssl3/portfile.cmake
- ports/openssl3/vcpkg.json
- versions/baseline.json
- versions/o-/openssl3.json
Update to the latest realese.
* https://github.com/openssl/openssl/releases/tag/openssl-3.1.3
* #108
* `x64-uwp`
* `x64-osx`
* `arm64-osx`
* `x64-linux`
* `arm64-ios`
```json
{
{
"kind": "git",
"packages": [
"openssl3"
],
}
]
}
```
> [openssl3] Update to 3.1.3

- ports/directml/portfile.cmake
- ports/directml/vcpkg.json
- versions/baseline.json
- versions/d-/directml.json
Update to latest release
* https://www.nuget.org/packages/Microsoft.AI.DirectML
* #109
* `x64-linux`
```json
{
{
"kind": "git",
"packages": [
"directml"
],
}
]
}
```
> [directml] update to 1.13.0

- .github/workflows/build-macos.yml
- .github/workflows/build-ubuntu.yml
- .github/workflows/build-windows.yml
- scripts/gh-cache-cleanup.ps1
Resolve #147
* https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
> CI: Rename workflow jobs and create a PowerShell script to cleanup GitHub Actions caches

- ports/nvidia-cnmem/portfile.cmake
- ports/nvidia-cnmem/vcpkg.json
- ports/nvidia-tools-extension-sdk/portfile.cmake
- ports/nvidia-tools-extension-sdk/vcpkg.json
- test/self-hosted-cuda.json
- versions/baseline.json
- versions/n-/nvidia-cnmem.json
- versions/n-/nvidia-tools-extension-sdk.json
Install NVTX3 headers. No `dependencies`.
* https://github.com/NVIDIA/NVTX/releases/tag/v3.1.0
* (URL for API documents)
* `x64-linux`
```json
{
{
"kind": "git",
"packages": [
"nvidia-tools-extension-sdk"
],
}
]
}
```
> [nvidia-tools-extension-sdk] Create a new port

- ports/onnx/fix-cmake.patch
- ports/onnx/portfile.cmake
- ports/onnx/vcpkg.json
- versions/baseline.json
- versions/o-/onnx.json
* Help #212
* #212
* `x64-osx`
* `x64-linux`
```json
{
{
"kind": "git",
"packages": [
"onnx"
],
}
]
}
```
> [onnx] Install proto, proto3 files

- ports/nvidia-cutlass/fix-cmake.patch
- ports/nvidia-cutlass/portfile.cmake
- ports/nvidia-cutlass/vcpkg.json
- test/self-hosted.json
- versions/baseline.json
- versions/n-/nvidia-cutlass.json
* Support 2 features, `tests` and `tools`
* Enable CuDNN, CuBLAS https://github.com/NVIDIA/cutlass/blob/7d49e6c7e2f8896c47f586706e67e1fb215529dc/CMakeLists.txt#L727-L728
* https://github.com/NVIDIA/cutlass/tree/v3.5.0
```json
{
{
"kind": "git",
"packages": [
"nvidia-cutlass"
],
}
]
}
```
> [nvidia-cutlass] support feature: tests, tools

- .circleci/config.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-ubuntu.yml
- .github/workflows/build-windows-hosted.yml
- .github/workflows/build-windows.yml
- azure-pipelines.yml
- test/azure-port-arm64-windows.txt
- test/self-hosted.json
- test/vcpkg.json
Update CI YAML files, vcpkg related configurations, and environment variables
* https://github.com/actions/runner-images
* https://circleci.com/developer/orbs
* https://circleci.com/developer/orbs/orb/circleci/android
> CI update for 2024 3Q releases

- ports/abseil/portfile.cmake
- ports/abseil/vcpkg.json
- versions/a-/abseil.json
- versions/baseline.json
Change to the LTS release version
* https://github.com/abseil/abseil-cpp/releases/tag/20240722.0
* #220 
no changes
```json
{
{
"kind": "git",
"packages": [
"abseil"
],
}
]
}
```
> [abseil] Update to 20240722.0

- ports/directml/portfile.cmake
- ports/directml/vcpkg.json
- versions/baseline.json
- versions/d-/directml.json
Update to the latest NuGet release
* https://www.nuget.org/packages/Microsoft.AI.DirectML/1.15.2
* https://github.com/microsoft/DirectML/blob/master/Releases.md
* Windows triplets
* `x64-linux`
```json
{
{
"kind": "git",
"packages": [
"directml"
],
}
]
}
```
> [directml] Update to 1.15.2

- .circleci/config.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-ubuntu.yml
- .github/workflows/build-windows-hosted.yml
- .github/workflows/build-windows.yml
- .github/workflows/deploy.yml
- azure-pipelines.yml
- scripts/template.json
Update the files for 2024-3Q
* https://github.com/microsoft/vcpkg/releases/tag/2024.08.23
> Create deploy.tml, Use vcpkg 2024.08.23

- .circleci/config.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-ubuntu.yml
- .github/workflows/build-windows-hosted.yml
- .github/workflows/build-windows.yml
- .github/workflows/deploy.yml
Use AWS S3 CLI tool to reduce network traffic cost
* https://github.com/luncliff/vcpkg-registry/pull/239 (previous work)
> CI: Fix CircleCI configuration, use AWS S3 binary caching

- .github/dependabot.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-ubuntu.yml
- .github/workflows/build-windows.yml
* Create dependabot.yml
* Use AWS CLI configure before binarycaching
* https://docs.github.com/en/code-security/dependabot
* #249
> CI: Use AWS CLI configure, Create a minimal Dependabot setting

- .circleci/config.yml
- .github/dependabot.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-ubuntu.yml
- .github/workflows/build-windows-hosted.yml
- .github/workflows/build-windows.yml
- .github/workflows/gh-pages.yml
- mkdocs.yml
* Update workflow YAML files
* Use `[skip ci] ` prefix in dependabot.yml
* https://squidfunk.github.io/mkdocs-material/plugins/offline/
> Docs: ignore 'docs' branch, depndabot for requirements.txt

- ports/dlpack/fix-cmake.patch
- ports/dlpack/portfile.cmake
- ports/dlpack/vcpkg.json
- test/azure-port-android.txt
- versions/baseline.json
- versions/d-/dlpack.json
Update to the latest version
* https://github.com/dmlc/dlpack/releases/tag/v1.0
* #150 
Previous work failed to build with NDK 27
> [dlpack] Update to v1.0

- ports/onnxruntime/fix-cmake.patch
- ports/onnxruntime/portfile.cmake
- ports/onnxruntime/vcpkg.json
- test/azure-port-android.txt
- test/azure-port-ios.txt
- versions/baseline.json
- versions/o-/onnxruntime.json
Remove `"supports"` field in the vcpkg.json
* Check the changed files
* `arm64-ios`
> [onnxruntime] Support Android, iOS build

- ports/sse2neon/portfile.cmake
- ports/sse2neon/vcpkg.json
- test/vcpkg.json
- versions/baseline.json
- versions/s-/sse2neon.json
* Create a new port for future works
* https://github.com/DLTcollab/sse2neon
* https://en.wikibooks.org/wiki/X86_Assembly/SSE
* `x86-linux`
> [sse2neon] Create a new port

- ports/liblzma/portfile.cmake
- ports/liblzma/vcpkg.json
- versions/baseline.json
- versions/l-/liblzma.json
Update version, license, and tool installation
* https://github.com/tukaani-project/xz/releases/tag/v5.6.2
* https://sourceforge.net/projects/lzmautils/files/
* https://cmake.org/cmake/help/latest/module/FindLibLZMA.html
* #190
> [liblzma] Update to 5.6.2

- ports/ml-dtypes/CMakeLists.txt
- ports/ml-dtypes/portfile.cmake
- ports/ml-dtypes/vcpkg.json
- versions/baseline.json
- versions/m-/ml-dtypes.json
* https://github.com/jax-ml/ml_dtypes/releases/tag/v0.5.0
* #198
> [ml-dtypes] Update to 0.5.0

- ports/glslang/portfile.cmake
- ports/glslang/private-headers.patch
- ports/glslang/vcpkg.json
- test/self-hosted.json
- test/vcpkg.json
- versions/baseline.json
- versions/g-/glslang.json
* Create a new port for future works.
* The port will install some internal headers
* https://github.com/KhronosGroup/glslang
* https://github.com/KhronosGroup/glslang/releases/tag/15.0.0
Currently targets Windows platforms
> [glslang] Create a new port with 15.0.0, install internal headers

- ports/onnx-optimizer/fix-cmakelists.patch
- ports/onnx-optimizer/portfile.cmake
- ports/onnx-optimizer/vcpkg.json
- versions/baseline.json
- versions/o-/onnx-optimizer.json
* Prepare 'python' feature support. It requires `onnx` port change
* https://github.com/onnx/optimizer/releases/tag/v0.3.19
> [onnx-optimizer] Update to 0.3.19

- azure-pipelines.yml
* Use steps.script instead of PowerShell step
* #301
* https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-script?view=azure-pipelines
* https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/powershell-v2?view=azure-pipelines
* https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/shell-script-v2?view=azure-pipelines
> CI: correct script for iOS build, Fix #301

- ports/libkineto/fix-cmake.patch
- ports/libkineto/fix-sources.patch
- ports/libkineto/portfile.cmake
- ports/libkineto/vcpkg.json
- versions/baseline.json
- versions/l-/libkineto.json
The port will be used for libtorch support
* https://github.com/facebookincubator/dynolog/commit/7570766213484a926908c884888cfb701577a9cb
* https://github.com/pytorch/kineto/commit/596126cba98181ce4a88e06aa1d602b6afd966dd
> [libkineto] Create a new port with the latest commit

- ports/opencl-headers/fix-headers.patch
- ports/opencl-headers/portfile.cmake
- ports/opencl-headers/vcpkg.json
- versions/baseline.json
- versions/o-/opencl-headers.json
Create a patch before version update.
* #204
> [opencl-headers] Disable test build of OpenCL-Headers

- .github/workflows/cleanup.yml
Run the PowerShell scripts automatically
* `scripts/gh-cleanup-runs.ps1`
* `scripts/gh-cleanup-cache.ps1`
> CI: try cleanup of build cache, cancelled runs when Pull Request is closed

- ports/coreml-tools/portfile.cmake
- ports/coreml-tools/vcpkg.json
- versions/baseline.json
- versions/c-/coreml-tools.json
* Resolve #311 
* https://github.com/luncliff/vcpkg-registry/pull/325
> [coreml-tools] Update to 8.2

- ports/nvidia-triton-client/fix-cmake.patch
- ports/nvidia-triton-client/portfile.cmake
- ports/nvidia-triton-client/vcpkg.json
- ports/nvidia-triton-common/portfile.cmake
- ports/nvidia-triton-common/vcpkg.json
- ports/nvidia-triton-core/fix-cmake.patch
- ports/nvidia-triton-core/fix-sources.patch
- ports/nvidia-triton-core/portfile.cmake
- ports/nvidia-triton-core/vcpkg.json
- versions/baseline.json
- versions/n-/nvidia-triton-client.json
- versions/n-/nvidia-triton-common.json
- versions/n-/nvidia-triton-core.json
Use more later commits
* https://github.com/triton-inference-server/core/commit/d53c1f7f8bceb891041e85f0bbf96837fd5cd0bf
* https://github.com/triton-inference-server/common/commit/a6b410343234f9acaa5d615c19f5b38690b45dff
* https://github.com/triton-inference-server/client/commit/3d9424956ba14660f9447575928601d449919abd
* #221 
* ...
> [nvidia-triton-*] update ports to use late 2024, early 2025 commit

- ports/abseil/portfile.cmake
- ports/abseil/vcpkg.json
- versions/a-/abseil.json
- versions/baseline.json
* Resolve #329 
* https://github.com/abseil/abseil-cpp/releases/tag/20250127.0
> [abseil] update to 20250127.0 

- .github/workflows/build.yml
- .github/workflows/check-issue.yml
* https://github.com/actions/upload-artifact/releases/tag/v4.6.1
* https://github.com/actions/upload-artifact/tree/v4.6.1
> CI: upload build logs if the job fails

- .circleci/config.yml
- .github/workflows/build-windows-hosted.yml
- .github/workflows/build.yml
- .github/workflows/request-port-update.yml
- mkdocs.yml
* Fixed warnings of the workflows for GITHUB_OUTPUT
* https://github.com/microsoft/vcpkg/releases/tag/2025.03.19
* #334
* #331 
* #307
> CI: misc changes, use vcpkg 2025.03.19

- ports/llama-cpp/portfile.cmake
- ports/llama-cpp/vcpkg.json
- versions/baseline.json
- versions/l-/llama-cpp.json
Find Python3 executable with `vcpkg_find_acquire_prgoram(PYTHON3)`
* #338
> [llama-cpp] Fix Python3 search in OpenCL feature build

- ports/google-jni-bind/portfile.cmake
- ports/google-jni-bind/vcpkg.json
- versions/baseline.json
- versions/g-/google-jni-bind.json
* Resolve #361
* https://github.com/google/jni-bind/releases/tag/Release-1.2.1-beta
* #321
> [google-jni-bind] Update to 1.2.1-beta

- ports/fp16/portfile.cmake
- ports/fp16/vcpkg.json
- versions/baseline.json
- versions/f-/fp16.json
* Add `license` field
* Install headers with CMake `file` command
* #247
> [fp16] change header install, license

- ports/glslang/portfile.cmake
- ports/glslang/vcpkg.json
- versions/baseline.json
- versions/g-/glslang.json
* glslang-config.cmake needs fix because the `vcpkg_cmake_config_fixup` doesn't change the part
* #285
> [glslang] correct `find_package(glslang)`

- ports/glslang/portfile.cmake
- ports/glslang/vcpkg.json
- versions/baseline.json
- versions/g-/glslang.json
Update to more later version
* https://github.com/KhronosGroup/glslang/releases/tag/15.1.0
* #285
> [glslang] update to 15.1.0

- .github/copilot-instructions.md
- README.md
- docs/references.md
- triplets/arm64-android.cmake
- triplets/x64-android.cmake
- triplets/x64-windows.cmake
Add some documents to help GitHub Copilot work better with vcpkg related questions
* Overhaul https://github.com/luncliff/vcpkg-registry/blob/main/docs/references.md
* https://docs.github.com/en/copilot/customizing-copilot/adding-repository-custom-instructions-for-github-copilot
* https://code.visualstudio.com/docs/copilot/copilot-customization
* https://github.com/luncliff/luncliff/issues/4
> Docs: Create GitHub Copilot Instructions, minor triplet changes

- ports/cudnn-frontend/vcpkg.json
- ports/nvidia-cudnn-frontend/portfile.cmake
- ports/nvidia-cudnn-frontend/vcpkg.json
- versions/baseline.json
- versions/c-/cudnn-frontend.json
- versions/n-/nvidia-cudnn-frontend.json
* Resolve #384 
* https://github.com/NVIDIA/cudnn-frontend/releases/tag/v1.12.0
* #347
> [nvidia-cudnn-frontend] Update to v1.12.0

- ports/ml-dtypes/portfile.cmake
- ports/ml-dtypes/vcpkg.json
- versions/baseline.json
- versions/m-/ml-dtypes.json
Replace the line with `vcpkg_replace_string`
* #323 (previous work)
* Help #387
> [ml-dtypes] Fix include path of mxfloat.h file

- ports/miniaudio/portfile.cmake
- ports/miniaudio/vcpkg.json
- versions/baseline.json
- versions/m-/miniaudio.json
- Resolve https://github.com/luncliff/vcpkg-registry/issues/389
* https://github.com/mackron/miniaudio/releases/tag/0.11.22
* #200
> [miniaudio] Update to 0.11.22

- ports/onnxruntime/portfile.cmake
- ports/onnxruntime/vcpkg.json
- versions/baseline.json
- versions/o-/onnxruntime.json
- Resolve #374 
* https://github.com/microsoft/onnxruntime/releases/tag/v1.21.1
> [onnxruntime] Update to v1.21.1

- ports/d3d12-transition-layer/portfile.cmake
- ports/d3d12-transition-layer/vcpkg.json
- versions/baseline.json
- versions/d-/d3d12-transition-layer.json
Change to the later version
* https://github.com/microsoft/D3D12TranslationLayer/commit/1be92fcd9a7a6c19b0796e445adba39d760f9f5a
* #283
Windows platforms
> [d3d12-transition-layer] update to 2025-05-22

- ports/cpuinfo/portfile.cmake
- ports/cpuinfo/vcpkg.json
- versions/baseline.json
- versions/c-/cpuinfo.json
Change to more later version
* https://github.com/pytorch/cpuinfo/commit/e4cadd02a8b386c38b84f0a19eddacec3f433baa
* #372
> [cpuinfo] update to 2025-06-26

- ports/nvidia-cutlass/portfile.cmake
- ports/nvidia-cutlass/vcpkg.json
- versions/baseline.json
- versions/n-/nvidia-cutlass.json
Update to the later version
* #412 
* https://github.com/NVIDIA/cutlass/releases/tag/v3.9.1
> [nvidia-cutlass] update to version 3.9.1

- ports/tensorpipe/fix-cmakelists.patch
- ports/tensorpipe/portfile.cmake
- ports/tensorpipe/vcpkg.json
- versions/baseline.json
- versions/t-/tensorpipe.json
What a great commit gap...
- https://github.com/pytorch/tensorpipe/commit/af0118d13e52f5a08841464a768e01a0bf3e3075
* `x64-linux`
* `x64-osx`
> [tensorpipe] update to 2025-08-16
