- triplets/x64-ios-simulator.cmake
Fix wrong `VCPKG_TARGET_ARCHITECTURE`. It must be `x64`.
* `x64-ios-simulator`
> Fix wrong triplet: x64-ios-simulator.cmake

- azure-pipelines.yml
- ports/tensorflow-lite/fix-gpu-build.patch
- ports/tensorflow-lite/vcpkg.json
- versions/baseline.json
- versions/t-/tensorflow-lite.json
* Afterwork of #32 
* `x64-osx`
* `arm64-osx`
```bash
vcpkg install --overlay-triplets ./vcpkg-registry/triplets/ --overlay-ports ./vcpkg-registry/ports/ \
tensorflow-lite[gpu]:x64-osx tensorflow-lite[gpu]:arm64-osx 
```
```json
{
{
"kind": "git",
"packages": [
],
}
]
}
```
> [tensorflow-lite] fix arm64-osx build failure

- ports/tensorflow-lite/portfile.cmake
- ports/tensorflow-lite/vcpkg.json
- versions/baseline.json
- versions/t-/tensorflow-lite.json
* Project: [TensorFlow Lite](https://github.com/tensorflow/tensorflow/releases/tag/v2.7.1)
* 2022/02/03
* #39
* #32
```json
{
{
"kind": "git",
"packages": [
],
}
]
}
```
> [tensorflow-lite] port update to v2.7.1

- ports/libdispatch/portfile.cmake
- ports/libdispatch/vcpkg.json
- versions/baseline.json
- versions/l-/libdispatch.json
Resolve #24 
* Project: [Apple Swift GCD](apple/swift-corelibs-libdispatch)
* [5.5 (2021/09)](https://github.com/apple/swift-corelibs-libdispatch/releases/tag/swift-5.5-RELEASE)
* `arm-android`
`VCPKG_LIBRARY_LINKAGE` can be both `static` and `dynamic`.
```json
{
{
"kind": "git",
"packages": [
"libdispatch"
],
}
]
}
```
* https://github.com/apple/swift-corelibs-libdispatch/pull/568 (Special thanks for the PR!)
* #24
* #23
* #8
> [libdispatch] Support NDK 23+

- azure-pipelines.yml
- ports/xnvctrl/CMakeLists.txt
- ports/xnvctrl/portfile.cmake
- ports/xnvctrl/vcpkg.json
- versions/baseline.json
- versions/x-/xnvctrl.json
* Project: [NVIDIA/nvidia-settings](https://github.com/NVIDIA/nvidia-settings) libXNVCtrl
[Google/ANGLE](https://github.com/google/angle) is using old version of the library.
The work is using one of the tags, https://github.com/NVIDIA/nvidia-settings/releases/tag/515.43.04
See https://github.com/google/angle/tree/main/src/third_party/libXNVCtrl
* `x64-linux`
Requires X11. APT package `libx11-dev`, `libx11-xcb-dev` will be added.
```json
{
{
"kind": "git",
"packages": [
"xnvctrl"
],
}
]
}
```
> [xnvctrl] create a new port

- azure-pipelines.yml
- ports/tensorflow-lite/fix-cmake-ios.patch
- ports/tensorflow-lite/portfile.cmake
- ports/tensorflow-lite/vcpkg.json
- versions/baseline.json
- versions/t-/tensorflow-lite.json
* Project: [TensorFlow Lite v2.8.0](https://github.com/tensorflow/tensorflow/releases/tag/v2.8.0)
* 2022/02/03
* #46 
* #47
* `arm64-ios`
> [tensorflow-lite] Support ios triplets

- ports/zlib-ng/portfile.cmake
- ports/zlib-ng/vcpkg.json
- versions/baseline.json
- versions/z-/zlib-ng.json
* Project: https://github.com/zlib-ng/zlib-ng
* 2021/12/24
Most of the triplets
```ps1
vcpkg install --overlay-ports "./vcpkg-registry/ports/"  zlib-ng[zlib-compat]
```
```json
{
{
"kind": "git",
"packages": [
"zlib-ng"
],
}
]
}
```
> [zlib-ng] update to 2.0.6

- ports/openssl3/portfile.cmake
- ports/openssl3/vcpkg.json
- versions/baseline.json
- versions/o-/openssl3.json
* Project: [OpenSSL 3.0.4](https://github.com/openssl/openssl/releases/tag/openssl-3.0.4)
* 2022/06
Most of the triplets.
```ps1
vcpkg install --overlay-ports "./vcpkg-registry/ports/ " openssl3
```
```json
{
{
"kind": "git",
"packages": [
"openssl3"
],
}
]
}
```
> [openssl3] update to 3.0.4

- .circleci/config.yml
- .circleci/port-uwp.txt
- .circleci/port-windows.txt
- azure-pipelines.yml
CircleCI provides more storage than Azure Pipelines.
Port `onnxruntime` requires over 13GB storage for build output.
CircleCI Windows build will cover them.
> CI: Support CircleCI for Windows port that requires large storage

- ports/fft2d/portfile.cmake
- ports/fft2d/vcpkg.json
- versions/baseline.json
- versions/f-/fft2d.json
`fft2d`'s `portfile.cmake` fails to rename the header files. Use [`file(COPY)`](https://cmake.org/cmake/help/latest/command/file.html#copy)
```json
{
{
"kind": "git",
"packages": [
"fft2d"
],
}
]
}
```
> [fft2d] fix header copy failure

- azure-pipelines.yml
- ports/system-qt5/LICENSE
- ports/system-qt5/portfile.cmake
- ports/system-qt5/qt5_make_path_options.cmake
- ports/system-qt5/vcpkg-port-config.cmake
- ports/system-qt5/vcpkg.json
- ports/system-qt6/LICENSE
- ports/system-qt6/portfile.cmake
- ports/system-qt6/qt6_make_path_options.cmake
- ports/system-qt6/vcpkg-port-config.cmake
- ports/system-qt6/vcpkg.json
- versions/baseline.json
- versions/s-/system-qt5.json
- versions/s-/system-qt6.json
* Project: [Qt Framework](https://www.qt.io/)
* Versions:
* https://doc.qt.io/qt-5.15/ (5.15.2+)
* https://doc.qt.io/qt-6/ (6.2+)
In vcpkg.json file,
```json
{
"dependencies": [
{
"name": "system-qt6",
"host": true
}
]
}
```
In `portfile.cmake` file,
```cmake
qt6_make_path_options(qt6_path_options WITH_TOOLS
COMPONENTS
Gui Widgets
)
vcpkg_cmake_configure(
SOURCE_PATH "${SOURCE_PATH}"
OPTIONS
${qt6_path_options}
)
```
* `x64-osx`, `arm64-osx`
```json
{
{
"kind": "git",
"packages": [
"system-qt5",
"system-qt6"
],
}
]
}
```
> [system-qt5,system-qt6] Host port for Qt framework

- ports/openssl3/portfile.cmake
- ports/openssl3/vcpkg.json
- versions/baseline.json
- versions/o-/openssl3.json
* Project: [OpenSSL/OpenSSL](https://github.com/openssl/openssl)
* Version: "3.0.6" https://github.com/openssl/openssl/releases/tag/openssl-3.0.6
```json
{
{
"kind": "git",
"packages": [
"openssl3"
],
}
]
}
```
> [openssl3] update to 3.0.6

- ports/openssl3/portfile.cmake
- ports/openssl3/vcpkg.json
- versions/baseline.json
- versions/o-/openssl3.json
* Project: [OpenSSL/OpenSSL](https://github.com/openssl/openssl/tree/openssl-3.0.7)
* Version: "3.0.7" https://github.com/openssl/openssl/tree/openssl-3.0.7
Previous Work #70 #69 
Every triplets
```json
{
{
"kind": "git",
"packages": [
"openssl3"
],
}
]
}
```
> [openssl3] update to 3.0.7

- ports/libdispatch/fix-cmake.patch
- ports/libdispatch/fix-sources-windows.patch
- ports/libdispatch/vcpkg.json
- versions/baseline.json
- versions/l-/libdispatch.json
* Project: [[]()](https://github.com/apple/swift-corelibs-libdispatch)
* Version: "swift 5.5"
```json
{
{
"kind": "git",
"packages": [
"libdispatch"
],
}
]
}
```
> [libdispatch] fix failure from VC++ stdatomic.h

- ports/directml/portfile.cmake
- ports/directml/vcpkg.json
- versions/baseline.json
- versions/d-/directml.json
* https://www.nuget.org/packages/Microsoft.AI.DirectML/1.10.0
* Version: "1.10.0"
Seems like the package supports Xbox. But I don't have a plan to support it.
* `arm-w64indows`
* `arm-windows`
* `x64-linux`
```json
{
{
"kind": "git",
"packages": [
"directml"
],
}
]
}
```
> [directml] update to 1.10.0

- ports/apple-nio-ssl/portfile.cmake
- ports/apple-nio-ssl/swiftpm-product-dynamic.patch
- ports/apple-nio-ssl/swiftpm-product-static.patch
- ports/apple-nio-ssl/swiftpm-use-local.patch
- ports/apple-nio-ssl/vcpkg.json
- versions/a-/apple-nio-ssl.json
- versions/baseline.json
Bugfix of #82 `apple-nio-ssl` port.
Same version. Create/use 2 functions
* `swiftpm_generatate_xcodeproj`: Generate `.xcodeproj` from Package.swift (Swift Package Manager, SwiftPM)
* `xcodebuild_build_framework`: Build/Copy `.framework` from generated xcodeproj
* `x64-osx`
* `arm64-osx`
* `arm64-ios`
```json
{
{
"kind": "git",
"packages": [
"apple-nio-ssl"
],
}
]
}
```
> [apple-nio-ssl] Fix static/dynamic build with xcodebuild

- ports/directml/portfile.cmake
- ports/directml/vcpkg.json
- versions/baseline.json
- versions/d-/directml.json
Previous work #79 
* Project: https://github.com/microsoft/DirectML
* Version: "1.10.1" https://www.nuget.org/packages/Microsoft.AI.DirectML/
* `arm-windows`
* `x64-linux`
```json
{
{
"kind": "git",
"packages": [
"directml"
],
}
]
}
```
> [directml] update to 1.10.1

- ports/tensorflow-lite/portfile.cmake
- ports/tensorflow-lite/vcpkg.json
- versions/baseline.json
- versions/t-/tensorflow-lite.json
* https://github.com/tensorflow/tensorflow/releases/tag/v2.9.3
Same with current support
```json
{
{
"kind": "git",
"packages": [
],
}
]
}
```
> [tensorflow-lite] update to 2.9.3

- azure-pipelines.yml
- ports/google-jni-bind/CMakeLists.txt
- ports/google-jni-bind/portfile.cmake
- ports/google-jni-bind/vcpkg.json
- versions/baseline.json
- versions/g-/google-jni-bind.json
* https://github.com/google/jni-bind
Header only port. Currently considers Android JNI
* `arm-neon-android`
* `x86-android`
```json
{
{
"kind": "git",
"packages": [
"google-jni-bind"
],
}
]
}
```
> [google-jni-bind] create a new port

- ports/openssl3/portfile.cmake
- ports/openssl3/vcpkg.json
- versions/baseline.json
- versions/o-/openssl3.json
* https://github.com/openssl/openssl/releases/tag/openssl-3.1.0
All triplets for the registry
```json
{
{
"kind": "git",
"packages": [
"openssl3"
],
}
]
}
```
> [openssl3] update to 3.1.0

- ports/cpuinfo/build-clog.patch
- ports/cpuinfo/portfile.cmake
- ports/cpuinfo/vcpkg.json
- versions/baseline.json
- versions/c-/cpuinfo.json
* https://github.com/pytorch/cpuinfo 
* https://github.com/pytorch/cpuinfo/commit/eb4a6674bfe9cf91b63b9817412ae5f6862c8432
* `x64-uwp`
* `arm64-uwp`
```json
{
{
"kind": "git",
"packages": [
"cpuinfo"
],
}
]
}
```
> [cpuinfo] update to latest

- ports/zlib-ng/portfile.cmake
- ports/zlib-ng/vcpkg.json
- versions/baseline.json
- versions/z-/zlib-ng.json
* https://github.com/zlib-ng/zlib-ng/releases/tag/2.0.7
All supported triplets in the registry
```json
{
{
"kind": "git",
"packages": [
"zlib-ng"
],
}
]
}
```
> [zlib-ng] update to 2.0.7

- ports/metal-cpp/MetalCppConfig.cmake
- ports/metal-cpp/portfile.cmake
- ports/metal-cpp/vcpkg.json
- versions/baseline.json
- versions/m-/metal-cpp.json
* https://developer.apple.com/metal/cpp/ macOS 13 / iOS 16
* `x64-osx`
* `arm64-osx`
* `arm64-ios`
* `x64-ios-simulator`
```json
{
{
"kind": "git",
"packages": [
"metal-cpp"
],
}
]
}
```
> [metal-cpp] update to latest

- ports/openssl3/portfile.cmake
- ports/openssl3/vcpkg.json
- versions/baseline.json
- versions/o-/openssl3.json
* `openssl3` references https://github.com/openssl/openssl/releases/tag/openssl-3.1.2
> [openssl3] update to 3.1.2

- ports/farmhash/portfile.cmake
- ports/farmhash/usage
- ports/farmhash/vcpkg.json
- versions/baseline.json
- versions/f-/farmhash.json
No source changes.
Update portfile.cmake for later https://github.com/microsoft/vcpkg-tool versions.
* https://github.com/google/farmhash 
* https://github.com/microsoft/vcpkg/pull/20506
```json
{
{
"kind": "git",
"packages": [
"farmhash"
],
}
]
}
```
> [farmhash] support `find_package(farmhash)`

- ports/fft2d/CMakeLists.txt
- ports/fft2d/portfile.cmake
- ports/fft2d/vcpkg.json
- versions/baseline.json
- versions/f-/fft2d.json
Update portfile.cmake.
Support `find_package(fft2d)`
* https://github.com/petewarden/OouraFFT
* https://github.com/luncliff/vcpkg-registry/pull/105
* https://github.com/luncliff/vcpkg-registry/pull/46
```json
{
{
"kind": "git",
"packages": [
"fft2d"
],
}
]
}
```
> [fft2d] Support `find_package(fft2d)`

- ports/nsync/export-targets.patch
- ports/nsync/fix-install.patch
- ports/nsync/portfile.cmake
- ports/nsync/vcpkg.json
- versions/baseline.json
- versions/n-/nsync.json
Create a new port for `find_package(nsync)`.
https://github.com/microsoft/vcpkg mainstream is using `unofficial::` namespace for the package.
* https://github.com/google/nsync/releases/tag/1.26.0
* https://github.com/microsoft/vcpkg/pull/15714
* https://github.com/microsoft/vcpkg/pull/23811
```json
{
{
"kind": "git",
"packages": [
"nsync"
],
}
]
}
```
> [nsync] create a new port with 1.26.0

- ports/zenny-atomic/portfile.cmake
- ports/zenny-atomic/vcpkg.json
- versions/baseline.json
- versions/z-/zenny-atomic.json
* use `vcpkg-cmake` host dependency
* use `vcpkg_install_copyright`
* https://github.com/zenny-chen/simple-stdatomic-for-VS-Clang
* `x64-uwp`
```json
{
{
"kind": "git",
"packages": [
"zenny-atomic"
],
}
]
}
```
> [zenny-atomic] update port for later vcpkg versions

- ports/openssl/portfile.cmake
- ports/openssl/vcpkg.json
- ports/openssl1/portfile.cmake
- ports/openssl1/vcpkg.json
- ports/openssl3/portfile.cmake
- ports/openssl3/vcpkg.json
- versions/baseline.json
- versions/o-/openssl.json
- versions/o-/openssl1.json
- versions/o-/openssl3.json
Mac/iOS build requires `install_name_tool`
```
install_name_tool -id ... libcrypto.3.dylib
install_name_tool -change ... libcrypto.3.dylib
```
* Create an empty port `openssl` to `openssl3`
* Update `openssl1` to 1.1.1w
* https://github.com/microsoft/vcpkg/issues/30805
* https://github.com/openssl/openssl/releases/tag/OpenSSL_1_1_1w
* `x64-osx`
* `arm64-osx`
* `arm64-ios`
```json
{
{
"kind": "git",
"packages": [
"openssl3",
"openssl1",
"openssl"
],
}
]
}
```
> [openssl,openssl1,openssl3] Run `install_name_tool` for Apple dynamic triplet

- ports/coreml-tools/portfile.cmake
- ports/coreml-tools/vcpkg.json
- versions/baseline.json
- versions/c-/coreml-tools.json
Additional path to guess `site-packages/` folder
* https://github.com/apple/coremltools/releases
* `x64-osx`
* `arm64-osx`
* `arm64-ios`
```json
{
{
"kind": "git",
"packages": [
"coreml-tools"
],
}
]
}
```
> [coreml-tools] More candidates for `site-packages` folder

- ports/etcpak/CMakeLists.txt
- ports/etcpak/portfile.cmake
- ports/etcpak/vcpkg.json
- test/vcpkg.json
- versions/baseline.json
- versions/e-/etcpak.json
Create a new port. The projects were found in https://github.com/godotengine/godot/tree/4.1.2-stable/thirdparty#rvo2
* https://github.com/wolfpld/etcpak
* `x64-linux`
```json
{
{
"kind": "git",
"packages": [
"etcpak"
],
}
]
}
```
> [etcpak] Create a new port

- ports/tensorflow-lite/portfile.cmake
- ports/tensorflow-lite/vcpkg.json
- versions/baseline.json
- versions/t-/tensorflow-lite.json
No major changes.  
Preparing Upcoming 2.15.0 support which contains TFLite C API changes https://github.com/tensorflow/tensorflow/releases/tag/v2.15.0
* https://github.com/tensorflow/tensorflow/releases/tag/v2.14.1
No triplet support changes
```json
{
{
"kind": "git",
"packages": [
],
}
]
}
```
> [tensorflow-lite] update to 2.14.1

- .github/workflows/build-windows.yml
- azure-pipelines.yml
- ports/onnxruntime/fix-cuda.patch
- ports/onnxruntime/portfile.cmake
- ports/onnxruntime/vcpkg.json
- test/self-hosted-cuda.json
- versions/baseline.json
- versions/o-/onnxruntime.json
Fix #136 
Tested with CUDA Toolkit 12.3.  
For some reason, MSBuild projects can't detect CUDA toolkit paths and NVCC outputs.  
Tried to provide `CMAKE_VS_PLATFORM_TOOLSET_CUDA` and some variables but they didn't either.
* Use the default CMake generator option(Ninja) in configure `vcpkg_cmake_configure`. 
* Patch `fix-cuda.patch` to add path information for CUPTI library which is installed under `"${CUDAToolkit_LIBRARY_ROOT}/extras/CUPTI/"`
Print more messages in portfile.cmake
* https://cmake.org/cmake/help/latest/variable/CMAKE_VS_PLATFORM_TOOLSET_CUDA.html
* #136 
```json
{
{
"kind": "git",
"packages": [
"onnxruntime"
],
}
] …
```
> [onnxruntime] Fix CUDA build

- ports/fbgemm/fix-cmakelists.patch
- ports/fbgemm/portfile.cmake
- ports/fbgemm/vcpkg.json
- versions/baseline.json
- versions/f-/fbgemm.json
Update the FBGEMM version
Supporting FBGEMM_GPU with another port or as a feature.
* https://github.com/pytorch/FBGEMM/releases/tag/v0.5.0
* `x64-linux`
* `x64-osx`
* `arm64-osx`
```json
{
{
"kind": "git",
"packages": [
"fbgemm"
],
}
]
}
```
> [fbgemm] update to v0.5.0

- ports/tensorpipe/fix-cmakelists.patch
- ports/tensorpipe/portfile.cmake
- ports/tensorpipe/vcpkg.json
- versions/baseline.json
- versions/t-/tensorpipe.json
The repository is archived.
* https://github.com/pytorch/tensorpipe
* `x64-linux`
* `x64-osx`
```json
{
{
"kind": "git",
"packages": [
"tensorpipe"
],
}
]
}
```
> [tensorpipe] update to 2022-05-14

- ports/onnx/portfile.cmake
- ports/onnx/vcpkg.json
- versions/baseline.json
- versions/o-/onnx.json
Help #136
Bring 2 CMake options into port features
```cmake
option(ONNX_DISABLE_EXCEPTIONS "Disable exception handling." OFF)
option(ONNX_DISABLE_STATIC_REGISTRATION "Disable static registration for onnx operator schemas." OFF)
```
```json
"features": {
"disable-exception": {
"description": "Disable exception handling"
},
"disable-static-generation": {
"description": "Disable static registration for onnx operator schemas"
}
}
```
* https://github.com/onnx/onnx
In v1.15.0 ...
https://github.com/onnx/onnx/blob/b86cc54efce19530fb953e4b21f57e6b3888534c/CMakeLists.txt#L27-L28
https://github.com/onnx/onnx/blob/b86cc54efce19530fb953e4b21f57e6b3888534c/setup.py#L46
Major triplets of the repository
```json
{
{
"kind": "git", …
```
> [onnx] support more features

- ports/onnx/portfile.cmake
- ports/onnx/vcpkg.json
- versions/baseline.json
- versions/o-/onnx.json
Update to later version
* https://github.com/onnx/onnx/releases/tag/v1.15.0
* #116
* #141
* `x64-linux`
* `x64-osx`
```json
{
{
"kind": "git",
"packages": [
"onnx"
],
}
]
}
```
> [onnx] update to 1.15.0

- ports/dlpack/portfile.cmake
- ports/dlpack/vcpkg.json
- versions/baseline.json
- versions/d-/dlpack.json
Create a new port for later version of ONNXRuntime
* https://github.com/dmlc/dlpack/releases/tag/v0.8
* `x64-linux`
* `x64-osx`, `arm64-osx`
```json
{
{
"kind": "git",
"packages": [
"dlpack"
],
}
]
}
```
> [dlpack] Create a new port with v0.8

- .circleci/config.yml
To reduce build time of the PR branches, Use binary caching feature with AWS S3
* Remove unused parts
* Use `bash.exe` for `circleci/aws-cli@4.1.2`
* https://circleci.com/developer/orbs/orb/circleci/aws-cli
> CI: Use AWS S3 binary caching in CircleCI build

- .circleci/config.yml
- azure-pipelines.yml
- ports/onnxruntime/fix-cmake.patch
- ports/onnxruntime/onnxruntime_vcpkg_deps.cmake
- ports/onnxruntime/portfile.cmake
- ports/onnxruntime/vcpkg.json
- test/self-hosted-cuda.json
- versions/baseline.json
- versions/o-/onnxruntime.json
* Remove NuGet usage in portfile.cmake. It is no longer used.
* Fix header search of Eigen3 in Linux build
* #151
* #152
* `x64-linux`
* `x64-osx`
```json
{
{
"kind": "git",
"packages": [
{
"name": "onnxruntime",
"features": [
"training",
"xnnpack"
]
}
],
}
]
}
```
> [onnxruntime] Fix use of Eigen3, remove NuGet executable usage

- ports/openssl3/portfile.cmake
- ports/openssl3/vcpkg.json
- versions/baseline.json
- versions/o-/openssl3.json
Install `openssl` CLI tool.
* https://github.com/openssl/openssl/tree/openssl-3.1.4
```json
{
{
"kind": "git",
"packages": [
{
"name": "openssl",
"featrures": [ "tools" ]
}
],
}
]
}
```
> [openssl3] Support `tools` feature

- ports/openssl3/portfile.cmake
- ports/openssl3/vcpkg.json
- versions/baseline.json
- versions/o-/openssl3.json
Update commit reference
* https://github.com/openssl/openssl/releases/tag/openssl-3.2.0
```json
{
{
"kind": "git",
"packages": [
"openssl3"
],
}
]
}
```
> [openssl3] update to 3.2.0

- ports/nvidia-triton-core/fix-cmake.patch
- ports/nvidia-triton-core/portfile.cmake
- ports/nvidia-triton-core/vcpkg.json
- test/self-hosted-cuda.json
- versions/baseline.json
- versions/n-/nvidia-triton-core.json
Create a new port with https://github.com/triton-inference-server/core
* https://github.com/triton-inference-server/core/commit/f0ff1e5de579e7c2322c78002b09b22463581f4c
* #159
* #160
* #161
* `x64-linux`
```json
{
{
"kind": "git",
"packages": [
"nvidia-triton-core"
],
}
]
}
```
> [nvidia-triton-core] Create a new port

- ports/nvidia-triton-client/fix-cmake.patch
- ports/nvidia-triton-client/portfile.cmake
- ports/nvidia-triton-client/vcpkg.json
- test/self-hosted-cuda.json
- versions/baseline.json
- versions/n-/nvidia-triton-client.json
Bring https://github.com/triton-inference-server/client to new port
* https://github.com/triton-inference-server/client
* #162 
* #160 
* #159 
* `x64-linux`
```json
{
{
"kind": "git",
"packages": [
"nvidia-triton-client"
],
}
]
}
```
> [nvidia-triton-client] Create a new port

- ports/onnxruntime/fix-clang-cl-simd-compile.patch
- ports/onnxruntime/fix-llvm-rc-unicode.patch
- ports/onnxruntime/portfile.cmake
- ports/onnxruntime/vcpkg.json
- versions/baseline.json
- versions/o-/onnxruntime.json
Add some patches to the onnxruntime port to handle issues with llvm-rc and clang-cl related to unicode in the rc file and clang-cl needing simd flags enabled when compiling SIMD code.
...
* `x64-windows` (MSVC and Clang-Cl)
> Patch onnxruntime to compile with clang-cl

- ports/opencl-headers/portfile.cmake
- ports/opencl-headers/vcpkg.json
- ports/opencl/portfile.cmake
- ports/opencl/vcpkg.json
- test/vcpkg.json
- versions/baseline.json
- versions/o-/opencl-headers.json
- versions/o-/opencl.json
Update `opencl-headers` and create `opencl` with the `v2023.12.14` version
* https://github.com/KhronosGroup/OpenCL-Headers
* https://github.com/KhronosGroup/OpenCL-CLHPP
* https://github.com/KhronosGroup/OpenCL-ICD-Loader
Does NOT support 
* `x64-uwp`
* `arm64-uwp`
```json
{
{
"kind": "git",
"packages": [
"opencl-headers",
"opencl"
],
}
]
}
```
> [opecl,opencl-headers] Create OpenCL ports from KhronosGroup repos

- .gitignore
- ports/opencl-on-dx12/fix-vcpkg.patch
- ports/opencl-on-dx12/portfile.cmake
- ports/opencl-on-dx12/vcpkg.json
- test/vcpkg.json
Create a new port for Windows DirectX 12
Used the latest commit at the moment
https://github.com/microsoft/OpenCLOn12/commits/master/
* https://github.com/microsoft/openclon12
* #164
* #166
* #167
```json
{
{
"kind": "git",
"packages": [
"opencl-headers",
"opencl-on-dx12"
],
}
]
}
```
> [opencl-on-dx12] Create a new port

- ports/openssl/portfile.cmake
- ports/openssl/vcpkg.json
- ports/openssl3/portfile.cmake
- ports/openssl3/vcpkg.json
- versions/baseline.json
- versions/o-/openssl.json
- versions/o-/openssl3.json
Update to the latest version
* https://github.com/openssl/openssl/releases/tag/openssl-3.2.1
* #169 (for future works)
All available triplets of the port
```json
{
{
"kind": "git",
"packages": [
"openssl",
"openssl3"
],
}
]
}
```
> [openssl3,openssl] update to v3.2.1

- ports/nvidia-cutlass/fix-cmake.patch
- ports/nvidia-cutlass/portfile.cmake
- ports/nvidia-cutlass/vcpkg.json
- test/self-hosted-cuda.json
- versions/baseline.json
- versions/n-/nvidia-cutlass.json
Create a new port with https://github.com/NVIDIA/cutlass
* https://github.com/NVIDIA/cutlass/releases/tag/v3.4.0
* `x64-linux`
```json
{
{
"kind": "git",
"packages": [
"nvidia-cutlass"
],
}
]
}
```
> [nvidia-cutlass] Create a new port with v3.4.0

- ports/directml/portfile.cmake
- ports/directml/vcpkg.json
- test/azure-port-arm64-windows.txt
- test/azure-port-linux.txt
- versions/baseline.json
- versions/d-/directml.json
* Add check of `x64-xbox-scarlett` in the portfile.cmake
* https://www.nuget.org/packages/Microsoft.AI.DirectML/
* https://microsoft.github.io/DirectML/
* `arm64ec-windows`
* `x64-xbox-scarlett`
* `x64-linux`
```json
{
{
"kind": "git",
"packages": [
"directml"
],
}
]
}
```
> [directml] Update to 1.13.1

- ports/nvidia-cutlass/portfile.cmake
- ports/nvidia-cutlass/vcpkg.json
- versions/baseline.json
- versions/n-/nvidia-cutlass.json
...
* https://github.com/NVIDIA/cutlass/releases/tag/v3.4.1
```json
{
{
"kind": "git",
"packages": [
"nvidia-cutlass"
],
}
]
}
```
> [nvidia-cutlass] update to v3.4.1

- ports/nvidia-nvbench/fix-cmake.patch
- ports/nvidia-nvbench/portfile.cmake
- ports/nvidia-nvbench/vcpkg.json
- test/self-hosted-cuda.json
- versions/baseline.json
- versions/n-/nvidia-nvbench.json
Create a new port from https://github.com/NVIDIA/nvbench
* https://github.com/NVIDIA/nvbench
* The project uses CMake scripts from https://github.com/rapidsai/rapids-cmake
* `x64-linux`
```json
{
{
"kind": "git",
"packages": [
"nvidia-nvbench"
],
}
]
}
```
> [nvidia-nvbench] Create a new port with latest commit

- .circleci/port-linux.txt
- ports/liblzma/portfile.cmake
- ports/liblzma/vcpkg.json
- test/self-hosted.json
- versions/baseline.json
- versions/l-/liblzma.json
Hotfix to prevent failure related to port `liblzma` 
* https://sourceforge.net/projects/liblzma/
* https://github.com/xz-mirror/xz
* https://openssf.org/blog/2024/03/30/xz-backdoor-cve-2024-3094/
* https://gist.github.com/thesamesam/223949d5a074ebc3dce9ee78baad9e27
* https://jfrog.com/blog/xz-backdoor-attack-cve-2024-3094-all-you-need-to-know/
For now, major triplets are in concern
* `x64-linux`
* `x64-osx`
```json
{
{
"kind": "git",
"packages": [
"liblzma"
],
}
]
}
```
> [liblzma] Create a new port with v5.4.6

- ports/cpuinfo/portfile.cmake
- ports/cpuinfo/vcpkg.json
- versions/baseline.json
- versions/c-/cpuinfo.json
Update to latest version
* https://github.com/pytorch/cpuinfo/commit/3c8b1533ac03dd6531ab6e7b9245d488f13a82a5
* https://github.com/pytorch/cpuinfo
* `x64-linux`
```json
{
{
"kind": "git",
"packages": [
"cpuinfo"
],
}
]
}
```
> [cpuinfo] update to 2024-04-18

- ports/fp16/portfile.cmake
- ports/fp16/vcpkg.json
- versions/baseline.json
- versions/f-/fp16.json
Update to the latest commit
* https://github.com/Maratyszcza/FP16/commit/581ac1c79dd9d9f6f4e8b2934e7a55c7becf0799
All triplets in the registry
```json
{
{
"kind": "git",
"packages": [
"fp16"
],
}
]
}
```
> [fp16] Update to later version

- .github/workflows/build-windows-hosted.yml
- ports/onnxruntime/vcpkg.json
- test/azure-port-arm64-windows.txt
- test/self-hosted-cuda.json
- test/self-hosted.json
- triplets/x64-linux.cmake
* Remove `tensorrt` feature. Will be resurrected in later port version
* Make `libXNNPACK.so` in Linux build to prevent undefined symbol error
Can't get the correct reason...
* #192
* `x64-linux`
* `x64-osx`
* `arm64-osx`
```json
{
{
"kind": "git",
"packages": [
"onnxruntime"
],
}
]
}
```
> [onnxruntime] Fix more CI failures

- ports/miniaudio/portfile.cmake
- ports/miniaudio/vcpkg.json
- test/vcpkg.json
- versions/baseline.json
- versions/m-/miniaudio.json
Update to latest Git tag 0.11.21
* https://github.com/mackron/miniaudio/releases/tag/0.11.21
* `x64-osx`
* `arm64-ios`
* `x64-linux`
```json
{
{
"kind": "git",
"packages": [
"miniaudio"
],
}
]
}
```
> [miniaudio] Update to 0.11.21

- .github/workflows/build-macos.yml
- .github/workflows/build-ubuntu.yml
- .github/workflows/build-windows-cuda.yml
- .github/workflows/build-windows-hosted.yml
- .github/workflows/build-windows.yml
- .github/workflows/gh-pages.yml
- README.md
* Use `${{ secrets.VCPKG_BINARY_SOURCES }}` in Self-hosted runners
* Update GitHub Action versions
* README.md recommends https://github.com/microsoft/vcpkg/releases/tag/2024.03.19
* #199
> CI: More fixes after #199

- ports/openjdk/linux-setup.cmake
- ports/openjdk/portfile.cmake
- ports/openjdk/vcpkg.json
- ports/openjdk/windows-cleanup.cmake
- ports/openjdk/windows-setup.cmake
- test/self-hosted.json
- test/vcpkg.json
- versions/baseline.json
- versions/o-/openjdk.json
Just for an experiment
* https://openjdk.org/projects/jdk
* https://github.com/openjdk/jdk/tree/jdk-23%2B10
```json
{
{
"kind": "git",
"packages": [
"openjdk"
],
}
]
}
```
> [openjdk] Create a new port with jdk-23+10

- ports/onnx/portfile.cmake
- ports/onnx/support-test.patch
- ports/onnx/vcpkg.json
- test/self-hosted-cuda.json
- test/self-hosted.json
- test/vcpkg.json
- versions/baseline.json
- versions/o-/onnx.json
* Support `onnx[test]`
* Rename existing feature with `vcpkg_check_features(INVERTED_FEATURES)`
* https://github.com/onnx/onnx/releases/tag/v1.15.0
* #143
* #141
* `x64-linux`
* `x64-osx`
```json
{
{
"kind": "git",
"packages": [
"onnx"
],
}
]
}
```
> [onnx] Support test build and rename features

- ports/onnx/portfile.cmake
- ports/onnx/vcpkg.json
- test/self-hosted-cuda.json
- test/self-hosted.json
- test/vcpkg.json
- versions/baseline.json
- versions/o-/onnx.json
Be explicit and follow the option's name
* #207
* `x64-linux`
* `x64-osx`
```json
{
{
"kind": "git",
"packages": [
"onnx"
],
}
]
}
```
> [onnx] Rename features to `disable-static-registration`, `disable-exception`

- ports/abseil/portfile.cmake
- ports/abseil/vcpkg.json
- test/azure-port-android.txt
- test/azure-port-arm64-uwp.txt
- test/azure-port-arm64-windows.txt
- test/azure-port-ios.txt
- test/azure-port-linux.txt
- test/azure-port-osx.txt
- test/vcpkg.json
- triplets/arm64-ios-simulator.cmake
- triplets/x64-ios-simulator.cmake
- versions/a-/abseil.json
- versions/baseline.json
New port to move faster than the vcpkg upstream.  
There are several differences.
* Library linkage is always `static`
* Consider if `VCPKG_CRT_LINKAGE` is `static`
* Always use C++ 17
* https://github.com/abseil/abseil-cpp/releases/tag/20240722.rc1
All triplets in the registry
`ios-simulator` triplets now uses higher SDK version
```json
{
{
"kind": "git",
"packages": [
"abseil"
],
}
]
}
```
> [abseil] Create a new port with 20240722.rc1

- ports/tensorflow-lite/portfile.cmake
- ports/tensorflow-lite/vcpkg.json
- versions/baseline.json
- versions/t-/tensorflow-lite.json
Preparing https://github.com/tensorflow/tensorflow/releases/tag/v2.17.0 for the registry
* https://github.com/tensorflow/tensorflow/releases/tag/v2.16.2
* #196
Same with current triplets
```json
{
{
"kind": "git",
"packages": [
],
}
]
}
```
> [tensorflow-lite] Update to v2.16.2

- ports/onnx/portfile.cmake
- ports/onnx/vcpkg.json
- versions/baseline.json
- versions/o-/onnx.json
Update to the later version. The port will be update again with https://github.com/onnx/onnx/releases/tag/v1.16.2
* Remove `python` feature. It will be resurrected later ...
* https://github.com/onnx/onnx/releases/tag/v1.16.1
* #212 
* `x64-linux`
* `x64-osx`
```json
{
{
"kind": "git",
"packages": [
"onnx"
],
}
]
}
```
> [onnx] Update to v1.16.1

- ports/google-jni-bind/CMakeLists.txt
- ports/google-jni-bind/portfile.cmake
- ports/google-jni-bind/vcpkg.json
- versions/baseline.json
- versions/g-/google-jni-bind.json
* Added `test` feature for future port test  
The feature failed in NDK 26 build
* https://github.com/google/jni-bind/releases/tag/Release-1.1.0-beta
* https://github.com/google/jni-bind/releases/tag/Release-1.0.0-beta bypassed
The port is header-only. All triplets are available.
```json
{
{
"kind": "git",
"packages": [
"google-jni-bind"
],
}
]
}
```
> [google-jni-bind] update to 1.1.0-beta

- ports/metal-cpp/portfile.cmake
- ports/metal-cpp/usage
- ports/metal-cpp/vcpkg.json
- versions/baseline.json
- versions/m-/metal-cpp.json
The port is too old for the latest Apple platform SDKs.
* Use the SDK names for `version-string`.  
The previous style, `version-date` didn't provide a proper description of the port.
* Install usage. Provide a link to GitHub repository https://github.com/bkaradzic/metal-cpp
* Remove `"supports"` constraint because the project is header-only.
* https://developer.apple.com/metal/cpp/
* #100
* #97 
The project is header-only, but it expects the target triplet is one of the Apple triplets
* `x64-osx`
* `arm64-osx`
* `arm64-ios`
```json
{
{
"kind": "git",
"packages": [
"metal-cpp"
],
}
]
}
```
> [metal-cpp] Update to macOS14.2_iOS17.2

- ports/fbgemm/fix-cmakelists.patch
- ports/fbgemm/portfile.cmake
- ports/fbgemm/vcpkg.json
- test/vcpkg.json
- versions/baseline.json
- versions/f-/fbgemm.json
The port is still CPU only.
* https://github.com/pytorch/FBGEMM/releases/tag/v0.8.0
* `x64-linux`
* `x64-osx`
```json
{
{
"kind": "git",
"packages": [
"fbgemm"
],
}
]
}
```
> [fbgemm] Update to v0.8.0

- .circleci/config.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-ubuntu.yml
- .github/workflows/build-windows-hosted.yml
- .github/workflows/build-windows.yml
- azure-pipelines.yml
- ports/winpixeventruntime/portfile.cmake
- ports/winpixeventruntime/vcpkg.json
- versions/baseline.json
- versions/w-/winpixeventruntime.json
Update to the latest release. What an old time ago...
* https://www.nuget.org/packages/WinPixEventRuntime
* https://devblogs.microsoft.com/pix/winpixeventruntime/
```json
{
{
"kind": "git",
"packages": [
"winpixeventruntime"
],
}
]
}
```
> [winpixeventruntime] Update to 1.0.240308001

- ports/d3d12-transition-layer/portfile.cmake
- ports/d3d12-transition-layer/vcpkg.json
- versions/baseline.json
- versions/d-/d3d12-transition-layer.json
Update to the later version
* https://github.com/microsoft/D3D12TranslationLayer/commit/315ca769aeed49bb84f72a8d5551951ba092ccd8
* #185
```json
{
{
"kind": "git",
"packages": [
"d3d12-transition-layer"
],
}
]
}
```
> [d3d12-transition-layer] Update to 2024-07-25

- ports/fp16/portfile.cmake
- ports/fp16/vcpkg.json
- versions/baseline.json
- versions/f-/fp16.json
Update to later commit
* https://github.com/Maratyszcza/FP16/commit/98b0a46bce017382a6351a19577ec43a715b6835
All triplets in the repository
```json
{
{
"kind": "git",
"packages": [
"fp16"
],
}
]
}
```
> [fp16] Update to 2024-06-20

- ports/libdispatch/portfile.cmake
- ports/libdispatch/vcpkg.json
- versions/baseline.json
- versions/l-/libdispatch.json
Update to the latest release. I forgot to make update ...
* https://github.com/apple/swift-corelibs-libdispatch/releases/tag/swift-5.10.1-RELEASE
* #189
> [libdispatch] Update to Swift 5.10.1

- ports/psimd/portfile.cmake
- ports/psimd/vcpkg.json
- versions/baseline.json
- versions/p-/psimd.json
Create the simplest port which installs a header file and license.
* https://github.com/Maratyszcza/psimd/commit/072586a71b55b7f8c584153d223e95687148a900
* https://github.com/microsoft/vcpkg/pull/16339
* https://github.com/microsoft/vcpkg/blob/master/ports/psimd/portfile.cmake
> [psimd] Create a new port with last commit

- ports/onnxruntime/cuDNN.cmake
- ports/onnxruntime/fix-cmake-cuda.patch
- ports/onnxruntime/fix-cmake.patch
- ports/onnxruntime/onnxruntime_external_deps.cmake
- ports/onnxruntime/portfile.cmake
- ports/onnxruntime/vcpkg.json
- versions/baseline.json
- versions/o-/onnxruntime.json
* overwrite cuDNN.cmake, onnxruntime_external_deps.cmake from main branch
* https://github.com/microsoft/onnxruntime/releases/tag/v1.19.0
* #227
* #237
no changes
> [onnxruntime] update to v1.19.0

- ports/dlpack/fix-cmake.patch
- ports/dlpack/vcpkg.json
- versions/baseline.json
- versions/d-/dlpack.json
Require CMake 3.22+ to build the port
* #251 
> [dlpack] Fix NDK 27+ CMake error

- ports/eigen3/portfile.cmake
- ports/eigen3/vcpkg.json
- versions/baseline.json
- versions/e-/eigen3.json
* Disable `CMAKE_Fortran_COMPILER` like Android build
* https://github.com/luncliff/vcpkg-registry/pull/50
* `arm64-ios`
> [eigen3] Disable Fortran in iOS build

- ports/nsync/fix-cmake.patch
- ports/nsync/vcpkg.json
- versions/baseline.json
- versions/n-/nsync.json
* `CMAKE_SYSTEM_NAME` check now considers `iOS`
* Recreate patch files
* Use C11 with `CMAKE_C_STANDARD`
* Use C++11 with `CMAKE_CXX_STANDARD`
* #234 
* #251 
* `arm64-ios`
> [nsync] Fix errors in iOS, Android build

- .circleci/config.yml
- ports/onnxruntime/portfile.cmake
- ports/onnxruntime/vcpkg.json
- versions/baseline.json
- versions/o-/onnxruntime.json
* Fix CircleCI build errors
* https://github.com/microsoft/onnxruntime/releases/tag/v1.19.2
* #263 
* #265
* #269
> [onnxruntime] Update to v1.19.2

- ports/metal-cpp/portfile.cmake
- ports/metal-cpp/vcpkg.json
- versions/baseline.json
- versions/m-/metal-cpp.json
Update to the later version
* https://developer.apple.com/metal/cpp/
* https://developer.apple.com/metal/cpp/files/metal-cpp_macOS15_iOS18-beta.zip
* https://github.com/bkaradzic/metal-cpp
* `x64-osx`
* `arm64-osx`
* `arm64-ios`
> [metal-cpp] Update to macOS15_iOS18-beta

- .github/workflows/gh-pages.yml
- docs/feature-binarycaching.md
- docs/feature-manifest.md
- docs/feature-registry.md
- docs/references.md
- mkdocs.yml
Create files for future writings.
> Docs: Create references.md, features-*.md files

- azure-pipelines.yml
`macos-latest` environment doesn't provide vcpkg
* Clone vcpkg repository
* Download vcpkg from Homebrew
* https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md
* https://formulae.brew.sh/formula/vcpkg
* https://github.com/microsoft/vcpkg/releases/tag/2024.09.30
> CI: Clone vcpkg 2024.09.30 in Azure Pipelines

- ports/smol-v/CMakeLists.txt
- ports/smol-v/portfile.cmake
- ports/smol-v/vcpkg.json
- test/self-hosted.json
- versions/baseline.json
- versions/s-/smol-v.json
Create a new port to update `google-filament`
* https://github.com/aras-p/smol-v
* https://github.com/aras-p/smol-v/commit/1de5258f0d55b160be5fabb1e3c88ef3dac19eba
Currently, targets Windows platform
> [smol-v] create a new port

- ports/nvidia-cudnn-frontend/portfile.cmake
- ports/nvidia-cudnn-frontend/vcpkg.json
- test/self-hosted.json
- versions/baseline.json
- versions/n-/nvidia-cudnn-frontend.json
Create port with https://github.com/NVIDIA/cudnn-frontend
* https://github.com/NVIDIA/cudnn-frontend/releases/tag/v1.7.0
> [nvidia-cudnn-frontend] Create a new port with v1.7.0

- ports/coreml-tools/fix-cmake.patch
- ports/coreml-tools/fix-sources.patch
- ports/coreml-tools/portfile.cmake
- ports/coreml-tools/vcpkg.json
- versions/baseline.json
- versions/c-/coreml-tools.json
Update to the latest version. Prepare `tensorflow-lite` update.
* https://github.com/apple/coremltools/releases/tag/8.0
* #219 
* #128 
* `x64-osx`
* `arm64-osx`
* `arm64-ios`
> [coreml-tools] Update to 8.0, detect Python3 version, site-packages folder

- .circleci/config.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-ubuntu.yml
- .github/workflows/build-windows-hosted.yml
- .github/workflows/build-windows.yml
- azure-pipelines.yml
* Update the vcpkg tag/commit
* Update the cache keys
* https://github.com/microsoft/vcpkg/releases/tag/2024.10.21
* https://github.com/microsoft/vcpkg/releases/tag/2024.09.30
> CI: Follow up vcpkg release 2024.10.21

- ports/openssl3/portfile.cmake
- ports/openssl3/vcpkg.json
- versions/baseline.json
- versions/o-/openssl3.json
Run fixup function after installtation
```cmake
vcpkg_cmake_config_fixup(CONFIG_PATH "lib/cmake/OpenSSL" PACKAGE_NAME OpenSSL)
```
* https://github.com/openssl/openssl/commit/c768ccebc718ea0ed6afc5147fe4079fff632cd6
> [openssl3] fixup OpenSSLConfig.cmake with vcpkg-cmake-config

- ports/google-jni-bind/portfile.cmake
- ports/google-jni-bind/vcpkg.json
- versions/baseline.json
- versions/g-/google-jni-bind.json
* https://github.com/google/jni-bind/releases/tag/Release-1.1.2-beta
* #228
> [google-jni-bind] Update to 1.1.2-beta

- ports/openssl3/portfile.cmake
- ports/openssl3/vcpkg.json
- versions/baseline.json
- versions/o-/openssl3.json
* https://github.com/openssl/openssl/releases/tag/openssl-3.4.0
* #248
> [openssl3] Update to 3.4.0

- ports/opencl-on-dx12/fix-d3d12transitionlayer.patch
- ports/opencl-on-dx12/portfile.cmake
- ports/opencl-on-dx12/vcpkg.json
- versions/baseline.json
- versions/o-/opencl-on-dx12.json
`<algorithm>` header is required to use `std::generator_n`
* https://en.cppreference.com/w/cpp/algorithm/generate_n
> [opencl-on-dx12] Fix D3D12TransitionLayer build failure

- ports/tensorpipe/TensorpipeConfig.cmake.in
- ports/tensorpipe/fix-cmakelists.patch
- ports/tensorpipe/vcpkg.json
- versions/baseline.json
- versions/t-/tensorpipe.json
Automatically finds `libuv`
```cmake
find_package(Tensorpipe) # find_dependency(libuv)
```
* https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#config-file-packages
* https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html
> [tensorpipe] better `find_package`, `find_dependency` for libuv

- .circleci/config.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-ubuntu.yml
- .github/workflows/build-windows-hosted.yml
- .github/workflows/build-windows.yml
- test/self-hosted.json
- test/vcpkg-configuration.json
- test/vcpkg.json
Prepare upcoming release of Feburary.
* Excluded `onnxruntime`
* CUDA failure is a known issue
* https://github.com/microsoft/vcpkg/releases/tag/2025.01.13
* Disabled `arm64-linux`
> CI: workflow update with vcpkg 2025.01.13

- ports/llama-cpp/fix-3rdparty.patch
- ports/llama-cpp/fix-cmake-ggml.patch
- ports/llama-cpp/fix-cmake-llama.patch
- ports/llama-cpp/portfile.cmake
- ports/llama-cpp/vcpkg.json
- test/self-hosted.json
- test/vcpkg.json
- versions/baseline.json
- versions/l-/llama-cpp.json
Update to more later version. Support more features with OpenCL, Vulkan, and CUDA
* https://github.com/ggerganov/llama.cpp/releases/tag/b4644
* #148
> [llama-cpp] Use later version with several GPU features

- .github/workflows/build.yml
- ports/spine-runtimes/CMakeLists.txt
- ports/spine-runtimes/fix-cmake.patch
- ports/spine-runtimes/portfile.cmake
- ports/spine-runtimes/vcpkg.json
- test/vcpkg.json
- versions/baseline.json
- versions/s-/spine-runtimes.json
Create a new port `spine-runtimes` with 4.2 branch. Visited 2025-02-14
* Resolve #319 
* https://github.com/microsoft/vcpkg/pull/27006
* https://github.com/EsotericSoftware/spine-runtimes/tree/4.2
> [spine-runtimes] Create a new port with 4.2 branch

- ports/godot/portfile.cmake
- ports/godot/vcpkg.json
- test/self-hosted.json
- test/vcpkg.json
- versions/baseline.json
- versions/g-/godot.json
Rework based on scripts of several years ago...
Use [SCons](https://github.com/SCons/scons/wiki) to build the Godot Engine's executables
https://github.com/godotengine/godot/blob/77dcf97d82cbfe4e4615475fa52ca03da645dbd8/SConstruct#L198
> [!CAUTION]
> The port is NOT a library port.  
> For the library, check https://github.com/microsoft/vcpkg/tree/master/ports/godot-cpp
* Resolve #322 
* https://github.com/godotengine/godot/releases/tag/4.3-stable
* https://github.com/microsoft/vcpkg/tree/master/ports/godot-cpp
> [godot] Support tool build and installation with 4.3-stable version

- .github/workflows/build.yml
- ports/godot/portfile.cmake
- ports/godot/vcpkg.json
- test/packages-apt.txt
- test/self-hosted.json
- test/vcpkg.json
- versions/baseline.json
- versions/g-/godot.json
* Build sources of https://esotericsoftware.com/spine-godot with `spine-runtimes` port
* https://github.com/EsotericSoftware/spine-runtimes/tree/4.2/spine-godot
* https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/custom_modules_in_cpp.html
* #324
* #320 
Currently, CCFLAGS customization causes build error. There is no support chage, but need to be cautious.
* `x64-linux`
* `x64-osx`, `arm64-osx`
> [godot] Support "spine-runtimes" feature with custom module build

- ports/abseil/portfile.cmake
- ports/abseil/vcpkg.json
- versions/a-/abseil.json
- versions/baseline.json
* Warn and modifty `ABSL_CONSUME_DLL` in the portfile.cmake
* Simplify the port description
* Reported in #328 
* #235
> [abseil] fix ABSL_CONSUME_DLL in installed header files

- .github/workflows/build.yml
- .github/workflows/cleanup.yml
- .github/workflows/weekly-maintenance.yml
- .gitignore
- scripts/update-portfile-sha512.ps1
* Run "validate" job before running "overlay"
* The job "overlay" now uses 3 matrix items. Triplets became optional step with the runner.OS
* Reorganize job dependencies
* Fix cleanup.yml
* New script: update-portfile-sha512.ps1 to make ease of SHA512 change in portfile.cmake 
* https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
> CI: update GitHub Actions workflows

- ports/metal-cpp/portfile.cmake
- ports/metal-cpp/vcpkg.json
- versions/baseline.json
- versions/m-/metal-cpp.json
* Use more later version in https://developer.apple.com/metal/cpp/
Future works
* update to https://developer.apple.com/metal/cpp/files/metal-cpp_macOS15.2_iOS18.2.zip
* https://github.com/bkaradzic/metal-cpp/tree/metal-cpp_macOS15_iOS18
* #271 
All Apple platform triplets
> [metal-cpp] update to macOS15_iOS18 

- ports/metal-cpp/portfile.cmake
- ports/metal-cpp/vcpkg.json
- versions/baseline.json
- versions/m-/metal-cpp.json
* Use more later version in https://developer.apple.com/metal/cpp/
* #343
* https://github.com/bkaradzic/metal-cpp/tree/metal-cpp_macOS15.2_iOS18.2
All Apple platform triplets
> [metal-cpp] update to macOS15.2_iOS18.2

- ports/llama-cpp/fix-3rdparty.patch
- ports/llama-cpp/portfile.cmake
- ports/llama-cpp/vcpkg.json
- test/self-hosted.json
- test/vcpkg-configuration.json
- test/vcpkg.json
- versions/baseline.json
- versions/l-/llama-cpp.json
* Resolve https://github.com/luncliff/vcpkg-registry/issues/337
* Fixed `openmp` feature dependency
* use `cpp-httplib` in `server` feature 
* https://github.com/ggml-org/llama.cpp/releases/tag/b4936
> [llama-cpp] update to b4936

- ports/nvidia-cnmem/fix-cmake.patch
- ports/nvidia-cnmem/portfile.cmake
- ports/nvidia-cnmem/vcpkg.json
- versions/baseline.json
- versions/n-/nvidia-cnmem.json
Support CMake configure with CMake 4.0 version
* https://cmake.org/cmake/help/v4.0/release/4.0.html
* https://github.com/NVIDIA/cnmem/commit/37896cc9bfc6536a8c878a1e675835c22d827821
> [nvidia-cnmem] Change `cmake_minimum_required` for CMake 4.0

- ports/opencl-headers/portfile.cmake
- ports/opencl-headers/vcpkg.json
- ports/opencl/portfile.cmake
- ports/opencl/vcpkg.json
- versions/baseline.json
- versions/o-/opencl-headers.json
- versions/o-/opencl.json
Bump to later release.
* CMake 4.0 fails to build the old version
* #204 
* https://github.com/KhronosGroup/OpenCL-Headers/releases/tag/v2024.10.24
* https://github.com/KhronosGroup/OpenCL-CLHPP/releases/tag/v2024.10.24
* https://github.com/KhronosGroup/OpenCL-ICD-Loader/releases/tag/v2024.10.24
> [opencl,opencl-headers] Update to v2024.10.24

- ports/tensorflow-lite/fix-sources.patch
- ports/tensorflow-lite/vcpkg.json
- versions/baseline.json
- versions/t-/tensorflow-lite.json
* see https://github.com/KhronosGroup/OpenCL-Headers/releases/tag/v2024.10.24
> The `cl_ndrange_kernel_command_properties_khr` type was generalized and renamed to `cl_command_properties_khr`.
The new version defines [macro `CL_KHR_COMMAND_BUFFER_EXTENSION_VERSION`](https://github.com/KhronosGroup/OpenCL-Headers/blob/4ea6df132107e3b4b9407f903204b5522fdffcd6/CL/cl_ext.h#L55) in `CL/cl_ext.h`.
Use this to distinguish new/old OpenCL Header version
* Before https://github.com/KhronosGroup/OpenCL-Headers/blob/v2024.05.08/CL/cl_ext.h#L47-L52
* After https://github.com/KhronosGroup/OpenCL-Headers/blob/v2024.10.24/CL/cl_ext.h#L47-L55
* #349
> [tensorflow-lite] Fix OpenCL 2024.10.24 build error

- ports/coreml-tools/fix-cmake.patch
- ports/coreml-tools/vcpkg.json
- versions/baseline.json
- versions/c-/coreml-tools.json
```./packages/coreml-tools_arm64-osx/
├── BUILD_INFO
├── CONTROL
├── debug
│   └── lib
│       ├── libcoremlpython.dylib
│       ├── libmilstoragepython.dylib
│       ├── libmlmodel.a
│       └── libmodelpackage.dylib
├── include
│   ├── mlmodel
│   │   └── format
│   │       ├── ArrayFeatureExtractor.pb.h
│   │       ├── ArrayFeatureExtractor.proto
│   │       ├── ...
│   │       └── WordTagger_enums.h
│   └── modelpackage
│       └── src
│           └── ModelPackage.hpp
├── lib
│   ├── libcoremlpython.dylib
│   ├── libmilstoragepython.dylib
│   ├── libmlmodel.a
│   └── libmodelpackage.dylib
├── share
│   └── coreml-tools
│       ├── copyright
│       └── vcpkg.spdx.json
└── tools
└── coreml-tools
├── enumgen
└── mlmodel_test_runner
13 directories, 114 files
```
* #311 
* …
> [coreml-tools] install modelpackage headers

- .github/workflows/request-port-update.yml
- ports/eigen3/portfile.cmake
- ports/eigen3/vcpkg.json
- versions/baseline.json
- versions/e-/eigen3.json
* Resolve https://github.com/luncliff/vcpkg-registry/issues/375
Be cautious about collisions of the ports' dependencies. Eigen `master` is not compatible with `3.4.0` now...
* https://gitlab.com/libeigen/eigen/-/commit/2265a5e025601d501903c772799ce29fb73c8efa
* https://gitlab.com/libeigen/eigen/-/tags
* #262
* #224
> [eigen3] update to 2025-04-23

- ports/abseil/portfile.cmake
- ports/abseil/vcpkg.json
- versions/a-/abseil.json
- versions/baseline.json
Prepare update to the latest version
- https://github.com/abseil/abseil-cpp/releases/tag/20250127.1
- https://github.com/abseil/abseil-cpp/releases/tag/20250512.0
> [abseil] update to 20250127.1

- ports/nvidia-tools-extension-sdk/portfile.cmake
- ports/nvidia-tools-extension-sdk/vcpkg.json
- ports/nvtx3/portfile.cmake
- ports/nvtx3/vcpkg.json
- versions/baseline.json
- versions/n-/nvidia-tools-extension-sdk.json
- versions/n-/nvtx3.json
- The port `nvidia-tools-extension-sdk` will be redirected to `nvtx3`
- `nvtx3` now supports `find_package`
```log
nvtx3 provides CMake targets:
find_package(nvtx3 CONFIG REQUIRED)
target_link_libraries(main PRIVATE nvtx3::nvtx3-c nvtx3::nvtx3-cpp)
```
* https://github.com/NVIDIA/NVTX/releases/tag/v3.2.0
* #418
> [nvtx3,nvidia-tools-extension-sdk] Create a new port with 3.2.0, make VCPKG_POLICY_EMPTY_PACKAGE

- ports/nvidia-cutlass/fix-find-cudnn.patch
- ports/nvidia-cutlass/portfile.cmake
- ports/nvidia-cutlass/vcpkg.json
- versions/baseline.json
- versions/n-/nvidia-cutlass.json
Using the `cudnn` port provides better CUDNN search
- https://github.com/microsoft/vcpkg/blob/master/ports/cudnn/FindCUDNN.cmake
- #412 
- https://github.com/microsoft/vcpkg/pull/46668
> [nvidia-cutlass] use FindCUDNN.cmake from vcpkg port 'cudnn'

- ports/llama-cpp/portfile.cmake
- ports/llama-cpp/vcpkg.json
- versions/baseline.json
- versions/l-/llama-cpp.json
Use the later release, which passed all CI workflows.
* https://github.com/ggml-org/llama.cpp/releases/tag/b6301
> [llama-cpp] Update to 2025-08-27

- ports/fp16/fix-bitcast.patch
- ports/fp16/portfile.cmake
- ports/fp16/vcpkg.json
- versions/baseline.json
- versions/f-/fp16.json
Use more later version. The port affects multiple ports, so need more detailed check.
- patch for bitcast (focusing on ARM64 Windows and x64 Windows)
- https://github.com/Maratyszcza/FP16/commit/3d2de1816307bac63c16a297e8c4dc501b4076df
> [fp16] update to 2025-08-17
